#%RAML 1.0
title: Employeedata-api
version: v1
description: THIS API IS USED TO DISPLAY EMPLOYEE INFORMATION
protocols: [Http,https]
types:
  Employee: !include datatypes/dataType.raml
  
/employees:
  post:
    body:
      application/json:
        example: !include example/employees.json
        type: Employee[]
    responses:
          201:
            body:
              application/json:
                example: {
                  "Message" : "Employee creation sucessful"
                }
  get:
    responses:
          200:
            body:
              application/json:
                example: !include example/employees.json

                  
                
/employees/{employeeId}:
  put:
    body:
      application/json:
        example: !include example/employee.json
       
    responses:
          200:
                body:
                      application/json:
                            example: {
                              "Message" :"Contact details updated"
                            }


  get:
    
    responses:
      200:
        body:
          application/json:
            example: !include example/employee.json 

  delete:
    
    responses:
            200:
              body:
                application/json:
                  example: {
                    "Message": "Employee details deleted sucessfully"
                  }

          
                        